/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package contactmanager;

import java.sql.*;
import org.apache.derby.jdbc.*;
import javax.swing.*;

/**
 *
 * @author Ryan
 */
public class ContactManager extends javax.swing.JFrame {

    private Connection con;
    private ResultSet rs;
    private Statement stmt;
    private final String dbURI = "jdbc:derby:contact;create=true";

    /**
     * Creates new form ContactManager
     */
    public ContactManager() {
        initComponents();
        setDBSystemDir();
        createDBTable();
        getResultSet();
        displayResults();
        pnlInsert.setVisible(false);
        pack();
    }

    private void setDBSystemDir() {
        //Decide on the database system directory: <userhome>/contact/
        String userHomeDir = System.getProperty("user.home", ".");
        String systemDir = userHomeDir + "/contact";

        //Set the database system directory
        System.setProperty("derby.system.home", systemDir);
    }

    private void createDBTable() {
        try {
            String sql = "create table contact (name varchar(30), email varchar(30), phone varchar(30))";
            DriverManager.registerDriver(new EmbeddedDriver());
            con = DriverManager.getConnection(dbURI);
            stmt = con.createStatement();
            stmt.execute(sql);
        } catch (SQLException e) {
            if (e.getErrorCode() != 30000) {
                //Error code 30000: Table exists = this is not an error!
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }

    private void getResultSet() {
        try {
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rs = stmt.executeQuery("select * from contact");
            //Result is scrollable and updateable.
            rs.first();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void displayResults() {
        try {
            txtName.setText(rs.getString("name"));
            txtEmail.setText(rs.getString("email"));
            txtPhone.setText(rs.getString("phone"));
        } catch (SQLException e) {
            if (e.getErrorCode() == 20000) {
                //Error code 20000: Invalid Cursor State = no records in DB!
                JOptionPane.showMessageDialog(this, "Click New to get started!");
                //If user deletes last record...
                txtName.setText("");
                txtEmail.setText("");
                txtPhone.setText("");
            } else {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInput = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        pnlInsert = new javax.swing.JPanel();
        btnInsert = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        pnlButtons = new javax.swing.JPanel();
        pnlNav = new javax.swing.JPanel();
        btnFirst = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        pnlControls = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple Contact Manager");

        jLabel1.setText("Name:");

        jLabel2.setText("Email:");

        jLabel3.setText("Phone:");

        txtName.setToolTipText("Name for contact");

        txtEmail.setToolTipText("Email address for contact");

        txtPhone.setToolTipText("Phone number for contact");

        javax.swing.GroupLayout pnlInputLayout = new javax.swing.GroupLayout(pnlInput);
        pnlInput.setLayout(pnlInputLayout);
        pnlInputLayout.setHorizontalGroup(
            pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInputLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmail))
                    .addGroup(pnlInputLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(9, 9, 9)
                        .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
                    .addGroup(pnlInputLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(7, 7, 7)
                        .addComponent(txtPhone)))
                .addContainerGap())
        );
        pnlInputLayout.setVerticalGroup(
            pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(pnlInput, java.awt.BorderLayout.PAGE_START);

        btnInsert.setText("Insert");
        pnlInsert.add(btnInsert);

        btnCancel.setText("Cancel");
        pnlInsert.add(btnCancel);

        getContentPane().add(pnlInsert, java.awt.BorderLayout.PAGE_END);

        pnlButtons.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        btnFirst.setText("<<");
        btnFirst.setToolTipText("First record");
        pnlNav.add(btnFirst);

        btnPrevious.setText("<");
        btnPrevious.setToolTipText("Previous record");
        pnlNav.add(btnPrevious);

        btnNext.setText(">");
        btnNext.setToolTipText("Next record");
        pnlNav.add(btnNext);

        btnLast.setText(">>");
        btnLast.setToolTipText("Last record");
        pnlNav.add(btnLast);

        pnlButtons.add(pnlNav);

        btnNew.setText("New");
        btnNew.setToolTipText("Create a new  record");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        pnlControls.add(btnNew);

        btnUpdate.setText("Update");
        btnUpdate.setToolTipText("Update the record");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        pnlControls.add(btnUpdate);

        btnDelete.setText("Delete");
        btnDelete.setToolTipText("Delete the record");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        pnlControls.add(btnDelete);

        pnlButtons.add(pnlControls);

        getContentPane().add(pnlButtons, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        //When new button is clicked:
        pnlButtons.setVisible(false);
        pnlInsert.setVisible(true);
        pack();

        try {
            rs.moveToInsertRow();
            displayResults();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // When update button is clicked:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // When delete button is clicked:
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ContactManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlControls;
    private javax.swing.JPanel pnlInput;
    private javax.swing.JPanel pnlInsert;
    private javax.swing.JPanel pnlNav;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
